server:
  port: 81



eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:6001/eureka
      #Eureka服务器集群
      #defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/
  instance:
    instance-id: mll-consumer-81
    prefer-ip-address: true     #访问路径可以显示IP地址

info:
  app.name: mll-microservice
  company.name: www.mll.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


spring:
  application:
    name: mll-consumer

#spring:
  #静态文件请求匹配方式
  mvc:
    static-path-pattern: /**
  #修改默认的静态寻址资源目录
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

  thymeleaf:
    encoding: UTF-8
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    #prefix: classpath:/templates/
    #suffix: .html